import type { Metadata } from "next";
import {ClerkProvider} from '@clerk/nextjs'
import { IBM_Plex, ActorFont } from "./fonts";
import "./globals.css";
import { HeaderServer } from "@/components/Header/HeaderServer";
import { FooterServer } from "@/components/Footer/FooterServer";
// import styles from "./layout.module.css"

export const dynamic = 'force-dynamic';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
	 <ClerkProvider>
    <html lang="en">
      <body
        className={`${IBM_Plex.variable} ${ActorFont.variable} antialiased`}
      >
		<HeaderServer/>
			<div >
        {children}
			</div>
		<FooterServer/>
      </body>
    </html>
	</ClerkProvider>
  );
}
