import type { Metadata } from "next";
import { IBM_Plex, ActorFont } from "./fonts";
import "./globals.css";
import { Header } from "@/components/Header/Header";
import { Footer } from "@/components/Footer/Footer";
// import styles from "./layout.module.css"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${IBM_Plex.variable} ${ActorFont.variable} antialiased`}
      >
		<Header/>
			<div >
        {children}
			</div>
		<Footer/>
      </body>
    </html>
  );
}
